apiVersion: "v1"
kind: "List"
items:
  - kind: "Secret"
    apiVersion: "v1"
    metadata:
      namespace: openldap
      name: "ldap-secret"
    data:
      # files in environment/* converted into base64 with file-to-base64.sh
      env.yaml: "IyBUaGlzIGlzIHR...="
      env.startup.yaml: "IyBUaGlzIGlz...="
