apiVersion: v1
kind: Service
metadata:
  namespace: openldap
  labels:
    app: ldap
  name: ldap-service
spec:
  type: NodePort
  ports:
    - name: openldap
      protocol: TCP
      port: 389
      targetPort: openldap
      nodePort: 389
    - name: ssl-ldap-port
      protocol: TCP
      port: 636
      targetPort: ssl-ldap-port
      nodePort: 636
  selector:
    app: ldap
