---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: openldap
  name: openldap-data-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  flexVolume:
    driver: alicloud/nas
    options:
      modeType: non-recursive
      path: /share/openldap-data
      # nas.aliyuncs.com
      server: xxx.cn-hangzhou.extreme.nas.aliyuncs.com
      vers: '3'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: openldap
  name: openldap-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: 3Gi
